Mvp
fuseio/subscription-service pull request #1
Opened 2021-02-21 11:52 UTC by mul53

2021-02-24 15:24 UTC, leonprou requested changes
Looks good!
Some small comments added.
We also would like to add `redis` to save the subscriptions map

2021-02-24 15:24 UTC, leonprou commented on package.json
> +    "start-prod": "NODE_ENV=production ts-node-transpile-only ./src/server.ts",
`NODE_ENV=production` is required right?
Should it be added to the node-skeleton?

2021-02-24 15:24 UTC, leonprou commented on src/services/event.ts
> +    addWalletTransferToEvent () {
can you add another handler that will monitor native Fuse transactions?

2021-02-24 15:24 UTC, leonprou commented on src/controllers/api/v1/subscriptions/index.ts
> +import SubscriptionService from '../../../../services/subscription'
can you use `moduleAliases` for this? writing from '@services/serviceName`

2021-02-24 15:24 UTC, leonprou commented on src/controllers/api/v1/subscriptions/index.ts
> +      next(e)
What happends when you use `next` with exception?
Usually we do not catch such errors, but have an error handler per application

2021-02-24 15:24 UTC, leonprou commented on src/services/event.ts
> +            await axios.post(subscription.webhookUrl, data)
I think you can remove the await here

2021-02-24 15:24 UTC, leonprou commented on src/services/subscription.ts
> +      this.subscriptions = new Map()
Can you move this map to `redis`? That way the storage will be both efficient and persistant

2021-02-24 15:24 UTC, leonprou commented on src/routes/api/v1/index.ts
> +  '/subscribe/wallet/transfers-to',
IMO `/wallet` part of the route is not needed. We can keep it as:
`subscribe/:eventName`, like `subscribe/transfers-to`

2021-02-24 15:24 UTC, leonprou commented on src/controllers/api/v1/subscriptions/index.ts
> +      const userService = Container.get(UserService)
Can you think of different names for this 3 services? They all names kinda same though functionality differ.
IMO at least one of them need to be changed to make it more clear

2021-02-25 09:52 UTC, mul53 commented on package.json
> +    "start-prod": "NODE_ENV=production ts-node-transpile-only ./src/server.ts",
yes, i can add that to the skeleton

2021-02-25 11:25 UTC, mul53 commented on src/services/event.ts
> +    addWalletTransferToEvent () {
Since this is on hold, I will resolve this

2021-03-07 08:33 UTC, leonprou approved these changes

2021-03-07 08:33 UTC, merged